/*
 * Copyright (c) 2023 by Brendan Haran, All Rights Reserved.
 * Use of this file or any of its contents is strictly prohibited without prior written permission from Brendan Haran.
 * Current File (firebase_options.dart) Last Modified on 12/22/22, 3:49 PM
 *
 */

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKRIvIJ2xzcW5cdztlnhG6ucl_DUn6Z4E',
    appId: '1:866365159801:web:7dc289b0b949f6341457a8',
    messagingSenderId: '866365159801',
    projectId: 'instructionarsenal',
    authDomain: 'instructionarsenal.firebaseapp.com',
    storageBucket: 'instructionarsenal.appspot.com',
    measurementId: 'G-ZXLR0FZBDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK6BFpxHAc4FU-s39hIzyfWzUZljnWhDA',
    appId: '1:866365159801:android:652d11011db35f811457a8',
    messagingSenderId: '866365159801',
    projectId: 'instructionarsenal',
    storageBucket: 'instructionarsenal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkfekteo4ETr2SgWTkScnpH0lvLTi2YCA',
    appId: '1:866365159801:ios:d708691ed8049f451457a8',
    messagingSenderId: '866365159801',
    projectId: 'instructionarsenal',
    storageBucket: 'instructionarsenal.appspot.com',
    iosClientId: '866365159801-96eocdgeqqr51571bqu623ba0b1505r0.apps.googleusercontent.com',
    iosBundleId: 'com.brendanharan.instructionArsenal',
  );
}
